# Generated by Django 4.2.16 on 2025-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Age", models.IntegerField()),
                ("Years_in_Business", models.IntegerField()),
                ("Annual_Income", models.FloatField()),
                ("Loan_Amount", models.FloatField()),
                ("Outstanding_Debt", models.FloatField()),
                ("Credit_Utilization_Rate", models.FloatField()),
                ("Number_of_Past_Loans", models.IntegerField()),
                ("Past_Defaults", models.IntegerField()),
                ("Payment_History_Score", models.FloatField()),
                ("Collateral_Value", models.FloatField()),
                ("Business_Type", models.CharField(max_length=100)),
                ("Region", models.CharField(max_length=100)),
                ("Economic_Sector", models.CharField(max_length=100)),
                ("predicted_risk", models.FloatField()),
                ("credit_score", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
