# Generated by Django 5.2.7 on 2025-10-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme_credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Years_in_Business', models.FloatField()),
                ('Annual_Income', models.FloatField()),
                ('Loan_Amount', models.FloatField()),
                ('Outstanding_Debt', models.FloatField()),
                ('Credit_Utilization_Rate', models.FloatField()),
                ('Number_of_Past_Loans', models.IntegerField()),
                ('Past_Defaults', models.IntegerField()),
                ('Payment_History_Score', models.FloatField()),
                ('Collateral_Value', models.FloatField()),
                ('Business_Type', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Economic_Sector', models.CharField(max_length=100)),
                ('predicted_risk', models.FloatField(blank=True, null=True)),
                ('credit_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
